import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";

import Navbar from "@/app/components/Navbar/navbar";
import LoginModal from "@/app/components/modal/LoginModal";
import RegisterModal from "@/app/components/modal/RegisterModal";
// import SearchModal from '@/app/components/modal/SearchModal';
// import RentModal from '@/app/components/modal/RentModal';

import ClientOnly from "./components/ClientOnly";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const font = Nunito({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ClientOnly>
          {/*<ToasterProvider/>*/}
          <LoginModal />
          <RegisterModal />
          {/*<SearchModal/>*/}
          {/*<RentModal/>*/}
          <Navbar />
        </ClientOnly>
        <div className="pb-20 pt-28">{children}</div>
      </body>
    </html>
  );
}
